### ISSUE TITLE
Corrupt db when checked

### ISSUE THREAD

**Issue by Wrexthor** [A15Bog/conanexilessql#1]
When running the CheckGameDB.bat it says Error: database disk image is malformed, when starting the server it restores a backed up version of db.

*edit*
I tried removing Reindex and Vacum and now it works fine, with only vacum it complain on indexes missing but might still start, have not tried it.

**Comment by A15Bog** [comment]
You need to run this when your server is shut down not online. The error you got happens when more than 1 thing are accessing the db.

**Comment by Wrexthor** [comment]
I copied the game.db to another folder (server was shut down), ran the script and then copied it back. Might not have been closed properly tho, does it need to be closed cleanly before this can be run?

**Comment by A15Bog** [comment]
Come into my teamspeak a15.soon.it pw: conan
I am uploading a bunch of new queries now I created and we can talk about the error you got, because i have seen it before, but it was seemingly because two things were open to the db.

**Comment by A15Bog** [comment]
Check out CONAN EXILES.txt i just uploaded for the previous queries contained in the .bat and a bunch of new.

**Comment by Wrexthor** [comment]
Managed to run the commands after a clean shutdown of db. Love the new stuff, didn't dare to add the timestamp to character modify and the export csv showed syntax error but the queries worked great (i use db browser for sqllite).
