### ISSUE TITLE
Request for delete structure trigger

### ISSUE THREAD

**Issue by yamakhalah** [A15Bog/conanexilessql#3]
Hi, first and foremost, thanks for your work.

I would to know if it could be possible to add a trigger who verify the timestamp each day at xx AM/PM:

if player has guild:

get every guild where each players  haven't been connected for XX days and then delete all structures of that guild.

else:

check if he haven't been connected for xx days then delete all structures of that layer

That might be amazing for conan des !

**Comment by A15Bog** [comment]
I updated the scripts today and they are in use on the #3 server on topconanservers.com, A15. The previous scripts were not 100%. The full version of decay along with the delete has also been added.
