### ISSUE TITLE
More frequent crashes after use

### ISSUE THREAD

**Issue by cokll** [A15Bog/conanexilessql#4]
Hi, first thanks for your .
I used this script The original 3-10 hour crash shortened to 10-30 minutes.
This is why?

**Comment by A15Bog** [comment]
I updated the scripts today and they are in use on the #3 server on topconanservers.com. The previous scripts can certainly cause issues. Sorry for the problem, these are properly tested.

**Comment by A15Bog** [comment]
I also added in scripts to fix the decay.
