### ISSUE TITLE
How to use? It seems that I can't run the current SQL.

### ISSUE THREAD

**Issue by cokll** [A15Bog/conanexilessql#5]
Thank you for your work.

SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open game.db
sqlite> .read 1.sql
Error: near line 2: duplicate column name: bog_time
Error: near line 3: no such column: old.i
Error: near line 11: trigger characters_bog_time_modify already exists
Error: near line 54: no such column: id
sqlite>

**Comment by A15Bog** [comment]
apologies, i had an incorrect id in the trigger. try running the new code which includes a drop statement along with the correct trigger

**Comment by A15Bog** [comment]
from your error it appears you already have a version of the trigger and already have the column installed. try the code again now, you will still get the error about duplicate column which is ok, but the other errors should go away now.

**Comment by cokll** [comment]
OK, thank you very much

**Comment by cokll** [comment]
I tried the latest SQL,I found no reduction in my database.Where did I go wrong?

Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open game.db
sqlite> .read 1.sql
Error: near line 12: no such trigger: characters_bog_time_modify
sqlite> .quit

**Comment by A15Bog** [comment]
A15 Discord: https://discord.gg/DGcQByW ||| Rules Steamgroup: A15Conan
